name: dropwizard-tut

pnConfig:
 url: https://dropwizard-tutorial.firebaseio.com

jerseyClient:
  timeout: 10000ms
  connectionTimeout: 10000ms
  timeToLive: 1 hour
  cookiesEnabled: false
  maxConnections: 2048
  maxConnectionsPerRoute: 2048
  keepAlive: 0s
  minThreads: 1
  maxThreads: 1000
  gzipEnabled: false
  gzipEnabledForRequests: false

dataSource:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost/dropwizard-tut

server:
  applicationConnectors:
  - type: http
    port: 9999
  adminConnectors:
  - type: http
    port: 9991

logging:
  level: INFO
  loggers:
   org.hibernate: WARN
  appenders:
  - type: console
    threshold: INFO

